export default {
  bob: 'https://imgur.com/QnIk5Fd.gif',
  bricks: 'https://imgur.com/2Us2ywA.jpg',
  corgi: 'https://imgur.com/dbF1iLj.gif',
  corgi_big: 'https://i.imgur.com/q0tMNDP.gif',
  csswg: 'https://imgur.com/oSgykm0.jpg',
  eye_anatomy: 'https://imgur.com/DilAJAp.jpg',
  eye_brightness: 'https://imgur.com/SB0yiYE.jpg',
  eye_discharge: 'https://imgur.com/Crj3tuM.jpg',
  eye_photosensors: 'https://imgur.com/dXb9gG0.jpg',
  eye_receptive: 'https://imgur.com/TA3YrjN.jpg',
  fodbold: 'https://imgur.com/hEP4l2G.jpg',
  grundtvig_1: 'https://imgur.com/tyA9Weq.jpg',
  grundtvig_2: 'https://imgur.com/bMazSSD.jpg',
  habesha: 'https://imgur.com/b6CkPRO.jpg',
  lucy: 'https://imgur.com/wPlWIHV.jpg',
  momondo_ease: 'https://imgur.com/xxpRaBx.jpg',
  momondo_linear: 'https://imgur.com/mZLK2ZY.jpg',
  nurse: 'https://imgur.com/smQQ7fk.jpg',
  savana: 'https://imgur.com/0I6Bs21.jpg',
  tiles: 'https://imgur.com/klfRiBu.jpg',
  twitter: 'https://imgur.com/Jqo3aYT.jpg',
  wow: 'https://imgur.com/wFKEUJ2.gif',
}
